name: Despliegue de Docker en AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login en DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y etiquetar la imagen Docker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nombre-de-repo:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nombre-de-repo:${{ github.sha }}

    - name: Desplegar en AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws ecs update-service --cluster nombre-de-cluster --service nombre-de-servicio --force-new-deployment
